apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-petclinic
  labels:
    apps.tanzu.vmware.com/workload-type: web
#    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: spring-petclinic
spec:
  source:
    git:
      url: https://github.com/bullblock/spring-petclinic-tap.git
      ref:
        branch: main
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
#  - name: testing_pipeline_matching_labels
#    value:
#      apps.tanzu.vmware.com/pipeline: test
#      apps.tanzu.vmware.com/language: java
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
